import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createHarnessAgents } from "../src/agents";
import { loadHarnessConfig } from "../src/config";

const args = process.argv.slice(2);
const check = args.includes("--check");
const projectRoot = args.find((arg) => arg !== "--check") ?? process.cwd();
const outputDir = join(projectRoot, "docs", "rendered-agents");
const agents = createHarnessAgents(loadHarnessConfig(projectRoot));

const names = Object.keys(agents).sort((a, b) => a.localeCompare(b));
const outputs = new Map<string, string>();

for (const name of names) {
  const agent = agents[name] ?? {};
  const prompt = typeof agent.prompt === "string" ? agent.prompt : "";
  const body = [
    `# ${name}`,
    "",
    "<!-- Generated by `bun run render-agents`. Do not edit by hand. -->",
    "",
    "## Agent configuration",
    "",
    "```json",
    JSON.stringify(summarizeAgent(agent), null, 2),
    "```",
    "",
    "## Full prompt",
    "",
    prompt.length > 0 ? prompt : "_No prompt: this agent is disabled or delegates to OpenCode built-in behavior._",
    "",
  ].join("\n");

  outputs.set(join(outputDir, `${name}.md`), body);
}

outputs.set(
  join(outputDir, "README.md"),
  [
    "# Rendered Agents",
    "",
    "Generated by `bun run render-agents` from `createHarnessAgents(loadHarnessConfig(projectRoot))`.",
    "Do not edit these files by hand; change prompt builders or agent config, then rerun the command.",
    "",
    "## Files",
    "",
    ...names.map((name) => `- [${name}](./${name}.md)`),
    "",
  ].join("\n"),
);

if (check) {
  const mismatches: string[] = [];
  for (const [filePath, expected] of outputs) {
    if (!existsSync(filePath)) {
      mismatches.push(`${filePath} (missing)`);
      continue;
    }

    const actual = readFileSync(filePath, "utf8");
    if (actual !== expected) {
      mismatches.push(filePath);
    }
  }

  if (mismatches.length > 0) {
    console.error("Rendered agent docs are stale or missing:");
    for (const mismatch of mismatches) console.error(`- ${mismatch}`);
    console.error("Run `bun run render-agents` to update them.");
    process.exit(1);
  }

  console.log(`Rendered agent docs are up to date (${outputs.size} files checked).`);
} else {
  mkdirSync(outputDir, { recursive: true });
  for (const [filePath, body] of outputs) {
    writeFileSync(filePath, body, "utf8");
  }

  console.log(`Rendered ${names.length} agents to ${outputDir}`);
}

function summarizeAgent(agent: Record<string, unknown>): Record<string, unknown> {
  const summary: Record<string, unknown> = {};
  for (const key of [
    "mode",
    "hidden",
    "disable",
    "description",
    "model",
    "variant",
    "temperature",
    "color",
    "permission",
  ]) {
    if (key in agent) summary[key] = agent[key];
  }
  return summary;
}
